cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name = 'cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name = 'cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name = 'cart_remove'),

]

coupons/urls.py
from django.urls import path
from . import views

app_name = 'coupons'

urlpatterns = [
    path('apply/', views.seller_coupon_apply, name='apply'),
    path('detach/<int:id>/', views.seller_coupon_detach, name='detach'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('cart/', include('cart.urls', namespace = 'cart')),
    path('', include('shop.urls', namespace = 'shop')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('seller/', include('sellers.urls', namespace='sellers')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/',views.admin_order_pdf,name='admin_order_pdf'),
]

shop/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name = 'product_list'),
    path('<slug:category_slug>/', views.product_list, name = 'product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name = 'product_detail'),
    path('add_product', views.add_product, name = 'add_product'),
    path('edit_product/<int:id>/<slug:slug>/', views.edit_product, name = 'edit_product'),
    path('delete_product/<int:id>/<slug:slug>/', views.delete_product, name = 'delete_product'),
    path('update_average', views.update_avg, name='update_average'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User
from decimal import Decimal
import time

class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='cart')

    def __str__(self):
        return 'Cart id {}. User {}.'.format(self.id, self.user)

    def __len__(self):
        return sum(item.quantity for item in self.items.all())

    def add(self, product, quantity = 1, update_quantity = False):
        item = self.get_item(product.id)
        if not item:
            CartItem.objects.create(cart=self, product=product, price=product.price, quantity=quantity)

        else:
            if update_quantity:
                item.quantity = quantity
            else:
                item.quantity += quantity

            item.save(update_fields=['quantity'])

    def remove(self, product_id):
        if self.items.filter(product__id = product_id):
            self.items.get(product__id = product_id).delete()

    def get_item(self, product_id):
        if self.items.filter(product__id = product_id):
            return self.items.get(product__id = product_id)
        return False

    def get_total_price(self):
        return sum(item.get_price() for item in self.items.all())

    def get_sum_discount(self):
        discount = Decimal('0')
        coupons = self.coupons.only('seller', 'discount')
        items = self.items.all()
        for coupon in coupons:
            discounted_items = items.filter(product__seller=coupon.seller)
            discount += coupon.discount / Decimal('100') * sum(i.get_price() for i in discounted_items)
        return discount

    def get_discount(self, coupon):
        discount = Decimal('0')
        items = self.items.all()
        discounted_items = items.filter(product__seller=coupon.seller)
        discount += coupon.discount / Decimal('100') * sum(i.get_price() for i in discounted_items)

        discount = round(discount,2)
        return discount

    def get_total_price_after_discount(self):
        return self.get_total_price() - self.get_sum_discount()

    def clear(self):
        self.items.all().delete()

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, related_name = 'items', on_delete = models.CASCADE)
    product = models.ForeignKey(Product, related_name = 'cart_items', on_delete = models.CASCADE)
    price = models.DecimalField(max_digits = 10, decimal_places = 2)
    quantity = models.PositiveIntegerField(default = 1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_price(self):
        return self.price * self.quantity

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices = PRODUCT_QUANTITY_CHOICES, coerce = int)
    update = forms.BooleanField(required = False, initial = False, widget = forms.HiddenInput())

cart/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Cart as CartModel, CartItem

from django.contrib.auth.signals import user_logged_in
from django.dispatch import receiver


@receiver(user_logged_in)
def on_login(sender, user, request, **kwargs):
    try:
        session_cart = request.session['cart']
        cart = get_object_or_404(CartModel, user=user)

        for key in session_cart:    # key is product id
            product = get_object_or_404(Product, id=key)
            if CartItem.objects.filter(product=product, cart=cart).exists():
                item = CartItem.objects.get(product=product, cart=cart)
                item.quantity = session_cart[str(key)]['quantity']
                item.save(update_fields=['quantity'])

            else:
                CartItem.objects.create(cart=cart, product=product, price=product.price, quantity=session_cart[str(key)]['quantity'])
    except:
        print('Error when adding products to cart.')



def cart_detail(request):

    if request.user.is_authenticated:
        coupon_apply_form = CouponApplyForm()
        cart = get_object_or_404(CartModel, user=request.user)
        return render(request, 'cart/detail_for_users.html', {'cart': cart, 'coupon_apply_form': coupon_apply_form})
    else:
        cart = Cart(request)
        return render(request, 'cart/detail.html', {'cart': cart})

@require_POST
def cart_add(request, product_id):
    product = get_object_or_404(Product, id = product_id)
    form = CartAddProductForm(request.POST)
    if request.user.is_authenticated:
        cart = get_object_or_404(CartModel, user=request.user)
    else:
        cart = Cart(request)

    if form.is_valid():
        cd = form.cleaned_data
        item = cart.get_item(product_id)
        if item:
            quantity = item.quantity if (request.user.is_authenticated) else item['quantity']

        if ((not item or cd['update']) and (product.quantity >=cd['quantity'])) or (item and product.quantity >= cd['quantity']+quantity):
            cart.add(product = product, quantity = cd['quantity'], update_quantity = cd['update'])
            return redirect('cart:cart_detail')

        messages.error(request, 'Add error. There is no so much {} in the store. There is only left {} item.'.format(product.name, product.quantity))
        return redirect(product.get_absolute_url())
    else:
        return HttpResponse('Bad request', status=400)


def cart_remove(request, product_id):
    if request.user.is_authenticated:
        cart = get_object_or_404(CartModel, user=request.user)
    else:
        cart = Cart(request)
    cart.remove(product_id)
    return redirect('cart:cart_detail')

templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %} Your shopping cart {% endblock %}
{% block content %}
<h1>Your shopping cart</h1>
<table class="cart">
  <thead>
    <tr>
      <th>Image</th>
      <th>Product</th>
      <th>Quantity</th>
      <th>Remove</th>
      <th>Unit price</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>

    {% for item in cart %}
      {% with product=item.product %}
      <tr>
        <td>
          <a href="{{ product.get_absolute_url }}">
            <img src="{% if product.image %}{{ product.image.url }} {% else %}{% static 'img/no_image.png' %}{% endif %}">
          </a>
        </td>
        <td> {{ product.name }} </td>
        <td>
          <form action="{% url 'cart:cart_add' product.id %}" method="post">
            {{ item.update_quantity_form.quantity }}
            {{ item.update_quantity_form.update }}
            <input type="submit" value="Update">
            {% csrf_token %}
          </form>
        </td>
        <td><a href="{% url 'cart:cart_remove' product.id %}"> Remove </a></td>
      <td class="num">${{ item.price }} </td>
      <td class="num">${{ item.total_price }} </td>
      </tr>
      {% endwith %}
    {% endfor %}

    <!-- {% if cart.coupon %}
    <tr class="subtotal">
      <td>Subtotal</td>
      <td colspan="4"></td>
      <td class="num">${{ cart.get_total_price|floatformat:"2" }}</td>
    </tr>
    <tr>
      <td>
        "{{ cart.coupon.code }}" coupon
        ({{ cart.coupon.discount }}% off)
      </td>
      <td colspan="4"></td>
      <td class="num neg">
        - ${{ cart.get_discount|floatformat:"2" }}
      </td>
    </tr>
    {% endif %} -->

    <tr class="total">
      <td>Total</td>
      <td colspan="4"></td>
      <td class="num">${{ cart.get_total_price|floatformat:"2" }}
    </tr>
  </tbody>
</table>

<!-- <p>Apply a coupon:</p>
<form action='{% url "coupons:apply" %}' method="post">
  {{ coupon_apply_form }}
  {% csrf_token %}
  <input type="submit" value="Apply">
</form> -->

<p class="text-right">
  <a href="{% url 'shop:product_list' %}" class="buttonlight">Continue shopping</a>
  <a href="{% url 'orders:order_create' %}"class="button">Checkout</a>
</p>
{% endblock %}

templates/cart/detail_for_users.html
{% extends "shop/base.html" %}
{% load static %}
{% load cart_tags %}
{% block title %} Your shopping cart {% endblock %}
{% block content %}
<h1>Your shopping cart</h1>
<table class="cart">
  <thead>
    <tr>
      <th>Image</th>
      <th>Product</th>
      <th>Quantity</th>
      <th>Remove</th>
      <th>Unit price</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
    {% for item in cart.items.all %}
      {% with product=item.product %}
      <tr>
        <td>
          <a href="{{ product.get_absolute_url }}">
            <img src="{% if product.image %}{{ product.image.url }} {% else %}{% static 'img/no_image.png' %}{% endif %}">
          </a>
        </td>
        <td> {{ product.name }} </td>
        <td>
          <form action="{% url 'cart:cart_add' product.id %}" method="post">
            {% show_item_form item.quantity %}
          </form>
        </td>
        <td><a href="{% url 'cart:cart_remove' product.id %}"> Remove </a></td>
      <td class="num">${{ item.price }} </td>
      <td class="num">${{ item.get_price }} </td>
      </tr>
      {% endwith %}
    {% endfor %}
    <tr class="subtotal">
      <td>Subtotal</td>
      <td colspan="4"></td>
      <td class="num">${{ cart.get_total_price|floatformat:"2" }}</td>
    </tr>
    {% for coupon in cart.coupons.all %}
      <tr>
        <td>
          <form action='{% url "coupons:detach" coupon.id %}' method="post">
            {% csrf_token %}
            <button type="input" class="close" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </form>
          "{{ coupon.code }}" coupon ({{ coupon.discount }}% off for products {{coupon.seller}})
        </td>
        <td colspan="4"></td>
        <td class="num neg">
          -${% show_discount cart coupon %}
        </td>
      </tr>
    {% empty %}
      <p>No Coupon</p>
    {% endfor %}
    <tr class="total">
      <td>Total</td>
      <td colspan="4"></td>
      <td class="num">${{ cart.get_total_price_after_discount|floatformat:"2" }}
    </tr>
  </tbody>
</table>

<p>Apply a coupon:</p>
<form action='{% url "coupons:apply" %}' method="post">
  {{ coupon_apply_form }}
  {% csrf_token %}
  <input type="submit" value="Apply">
</form>

<p class="text-right">
  <a href="{% url 'shop:product_list' %}" class="buttonlight">Continue shopping</a>
  <a href="{% url 'orders:order_create' %}" class="button">Checkout</a>
</p>
{% endblock %}

templates/cart/item_form.html
{{cart_item_form.quantity}}
{{cart_item_form.update}}
<input type="submit" value="Update">
{% csrf_token %}