cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name = 'cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name = 'cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name = 'cart_remove'),

]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('cart/', include('cart.urls', namespace = 'cart')),
    path('', include('shop.urls', namespace = 'shop')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('seller/', include('sellers.urls', namespace='sellers')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

sellers/urls.py
from django.urls import path
from . import views


app_name = 'sellers'

urlpatterns = [
    path('seller_registration/', views.seller_registration, name='seller_registration'),
]

shop/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name = 'product_list'),
    path('<slug:category_slug>/', views.product_list, name = 'product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name = 'product_detail'),
    path('add_product', views.add_product, name = 'add_product'),
    path('edit_product/<int:id>/<slug:slug>/', views.edit_product, name = 'edit_product'),
    path('delete_product/<int:id>/<slug:slug>/', views.delete_product, name = 'delete_product'),
    path('update_average', views.update_avg, name='update_average'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/models.py
from django.db import models
from django.shortcuts import reverse
from sellers.models import Seller
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db.models import Avg
from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
from datetime import datetime

class Category(models.Model):
    name = models.CharField(max_length = 200, db_index = True)
    slug = models.SlugField(max_length = 200, unique = True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    seller=models.ForeignKey(Seller, on_delete=models.CASCADE, related_name='products')
    category = models.ForeignKey(Category, related_name = 'products', on_delete = models.CASCADE)
    name = models.CharField(max_length = 200, db_index = True)
    slug = models.SlugField(max_length = 200, db_index = True)
    image = models.ImageField(upload_to = 'products/%Y/%m/%d', blank = True)
    description = models.TextField(blank = True)
    price = models.DecimalField(max_digits = 10, decimal_places = 2)
    available = models.BooleanField(default = True)
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now = True)
    quantity = models.PositiveIntegerField(default = 0)
    purchased_quantity = models.PositiveIntegerField(default = 0)
    rating_average = models.FloatField(default=0)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])


    def save(self, *args, **kwargs):
        if not self.id:
            self.image = self.compress_image(self.image)
        super(Product, self).save(*args, **kwargs)

    def compress_image(self, uploaded_image):
        img = Image.open(uploaded_image)
        outputIoStream = BytesIO()
        img = img.resize((400, 400))
        img.save(outputIoStream , format='JPEG', quality=80)
        outputIoStream.seek(0)
        uploaded_image = InMemoryUploadedFile(outputIoStream,'ImageField', "%s.jpg" % uploaded_image.name.split('.')[0], 'image/jpeg', None, None)
        return uploaded_image


class ProductRating(models.Model):
    rating = models.FloatField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='product_rating')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='rating')

    class Meta():
        ordering=['id']
        unique_together = (("user", "product"),)

    def __str__(self):
        return '{}-{}'.format(str(self.product), str(self.rating))


@receiver(post_save, sender=ProductRating)
def update_average(sender, instance, **kwargs):
    product = instance.product
    product.rating_average = product.rating.all().aggregate(Avg('rating'))['rating__avg']
    product.save(update_fields=['rating_average'])

class ProductReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='product_reviews')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='reviews')
    text = models.TextField(max_length=1000)
    date = models.DateTimeField(default=datetime.now, verbose_name='Date')

    class Meta():
        ordering=['id']

    def __str__(self):
        return '{} review .User {}'.format(str(self.product), str(self.user))

shop/forms.py
from django import forms
from .models import Product, ProductReview


class ProductAddForm(forms.ModelForm):
    field_order = ['category', 'name', 'description', 'image', 'price', 'quantity']
    class Meta:
        model = Product
        fields = {'category', 'name', 'description', 'image', 'price','quantity'}

class ProductEditForm(forms.ModelForm):
    field_order = ['category', 'name', 'description', 'image', 'price','quantity', 'available']
    class Meta:
        model = Product
        fields = {'category', 'name', 'description', 'image', 'price', 'quantity','available'}

class ProductReviewForm(forms.ModelForm):
    class Meta:
        model = ProductReview
        fields = {'text'}

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.contrib.auth.models import User
from shop.models import Category, Product, ProductRating
from cart.forms import CartAddProductForm
from .recommender import Recommender
from .forms import ProductAddForm, ProductEditForm
from sellers.models import Seller
from django.template.defaultfilters import slugify
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db.models import Avg
from django.contrib.auth.decorators import login_required

from .forms import ProductReviewForm

def product_list(request, category_slug = None):
    categories = Category.objects.all()
    products = Product.objects.filter(available = True)

    if category_slug:
        category = get_object_or_404(Category, slug = category_slug)
        products = products.filter(category = category)
    else:
        category = None

    context = {
        'category': category,
        'categories': categories,
        'products': products,
    }

    return render(request, 'shop/product/list.html', context)

def product_detail(request, id, slug):
    product = get_object_or_404(Product, id = id, slug = slug, available = True)
    cart_add_product_form = CartAddProductForm()
    product_review_form = ProductReviewForm()
    r = Recommender()
    recommended_products = r.suggest_products_for([product], 4)

    if request.method=='POST' and request.user.is_authenticated:
        review = ProductReviewForm(request.POST)

        if review.is_valid():
            new_review = review.save(commit=False)
            new_review.user = request.user
            new_review.product = product
            new_review.save()
            return redirect(product.get_absolute_url())

    context = {
        'product': product,
        'cart_add_product_form': cart_add_product_form,
        'recommended_products': recommended_products,
        'product_review_form': product_review_form
    }

    return render(request, 'shop/product/detail.html', context)

@login_required
def add_product(request):
    product_form = ProductAddForm()
    is_seller = False
    if request.user.is_authenticated and request.user.seller:
        is_seller = True
        if request.method == "POST":
            product_form = ProductAddForm(request.POST, request.FILES)
            if product_form.is_valid():
                new_product = product_form.save(commit=False)
                new_product.slug = slugify(new_product.name)
                new_product.seller = request.user.seller
                new_product.save()
                return redirect(reverse('shop:product_detail', args=[new_product.id, new_product.slug]))

    else:
        return HttpResponse("<h1>You are not seller</h1>", status=403)

    return render(request, 'shop/product/add_product.html', {'product_form': product_form, 'is_seller': is_seller})

@login_required(login_url='accounts/login/')
def edit_product(request, id, slug):
    product=get_object_or_404(Product, id=id, slug=slug)
    if request.user.is_authenticated:
        if request.user != product.seller.user and not request.user.is_superuser:
            raise PermissionDenied
        if request.method=='POST':
            product_edit_form = ProductEditForm(instance=product, data=request.POST, files=request.FILES)

            if product_edit_form.is_valid():
                product_edit_form.save()

            return redirect(reverse('shop:product_detail', args=[product.id, product.slug]))
        else:
            product_edit_form = ProductEditForm(instance=product)

    return render(request, 'shop/product/edit_product.html', {'product_edit_form': product_edit_form})

@login_required(login_url='accounts/login/')
def delete_product(request, id, slug):
    product=get_object_or_404(Product, id=id, slug=slug)
    if request.user.is_authenticated:
        if request.user != product.seller.user and not request.user.is_superuser:
            raise PermissionDenied
        product.delete()
        return redirect('shop:product_list')

@login_required
def update_avg(request):
    if request.is_ajax():
        product = get_object_or_404(Product, id=request.POST.get('id'))
        rating = request.POST.get('rating')
        if ProductRating.objects.filter(user=request.user, product=product).exists():
            obj = ProductRating.objects.get(user=request.user, product=product)
            obj.rating = rating
            obj.save(update_fields=['rating'])
            product.rating_average = product.rating.all().aggregate(Avg('rating'))['rating__avg']
            product.save(update_fields=['rating_average'])

        else:
            ProductRating.objects.create(user=request.user, product=product, rating=rating)

        return JsonResponse({'total_rating': product.rating_average})

    return HttpResponse('Bad request', status=400)

templates/shop/base.html
<!doctype html>
{% load static %}
{% load socialaccount %}

<html lang="en">
<head>
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,
initial-scale=1, shrink-to-fit=no">

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<!-- Custom fonts for this template "for index.heml" -->
<link href="{% static 'shop/vendor/fontawesome-free/css/all.min.css' %} " rel="stylesheet" type="text/css">

<!-- Custom fonts for this template -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<title>{% block title %}My shop{% endblock %}</title>
<!-- Custom scripts for this template -->
 <script src='{% static "shop/js/clean-blog.min.js" %}'></script>

 <!-- Custom styles for this template -->
 <link href="{% static 'shop/css/clean-blog.min.css' %}" rel="stylesheet">

<link href="{% static "css/base.css" %}" rel="stylesheet">
</head>


<body>
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="/"><i class="fa fa-home"></i>Home</a>
      <a class="navbar-brand" href="{% url 'shop:add_product' %}">Add Product</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link dropdown-toggle" href="#" id="userMenu"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {{ request.user.username }}
                </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                <a class="dropdown-item" href="{% url 'profile' request.user.id %}">My Profile</a>
                <a class="dropdown-item" href="{% url 'account_change_password'%}">Change password</a>
              <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'account_logout' %}">Log Out</a>
              </div>
              </li>
            </ul>
          {% else %}
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a  href="{% url 'account_login' %}" class="btn btn-outline-dark">Log In</a>
              </li>
              <li class="nav-item">
                <a href="{% url 'signup' %}" class="btn btn-primary btn-sm">Sign up</a>
              </li>
              <li class="nav-item">
                <a href="{% url 'sellers:seller_registration' %}" class="btn btn-primary btn-sm">Sign up as seller</a>
              </li>
            </ul>
          {% endif %}

        </ul>
      </div>

  </div>
  </nav>
  <br>
  <br>
  <div id="content">
    <div  class="cart" id = "subheader">
      {% with total_items=cart|length %}
        {% if total_items %}
          Your cart:
            <a href="{% url 'cart:cart_detail' %}">
              {{ total_items }} item{{ total_items|pluralize }},
              ${{ cart.get_total_price }}
            </a>
        {% else %}
        Your cart is empty.
        {% endif %}
      {% endwith %}
    </div>

    <!-- Show messages -->
    {% if messages %}
      {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error{% else %}{{ message.tags|title }}{% endif %}!</strong> {{ message }}
      </div>
      {% endfor %}
    {% endif %}

  {% block content %}


  {% endblock %}
  </div>
</body>
</html>

templates/shop/profile.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %} My profile {% endblock %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-6 img">
        {% if user.profiles.image %}
        <img src="{{user.profiles.image.url}}" alt="" class="avatar secondary-content" style="width: 250px;height: 250px;margin-top: -100px;margin-left: -200px; position: absolute; top: 50%;left: 50%;" usemap="#workmap">
        {% else %}
        <img src='https://svgshare.com/i/65U.svg' coords="100,0,82,126" alt="" class="avatar secondary-content" style="width: 250px;height: 250px;margin-top: -120px;margin-left: -200px; position: absolute; top: 50%;left: 50%;"/>
      </div>
      {% endif %}
      <div class="col-md-6 details">
        <p>
  	    <blockquote>{{user.first_name}}  {{user.last_name}}</blockquote>
          Username: {{user.username}} <br>
          Email: {{user.email}} <br>
          {% if is_seller %}
          Phone: {{user.seller.phone}}<br>
          Web Address: <a href="{{user.seller.web_address}}">{{user.seller.web_address}}</a><br>
          Company Name: {{user.seller.name}}<br>
          Country : {{user.seller.country}}, Province: {{user.seller.province}}, City: {{user.seller.city}}, Address: {{user.seller.address}}<br>
          {% endif %}
          Date joined: {{user.date_joined}}<br>
          {% if request.user == user %}
            <p><a class="btn btn-warning" href="{% url 'useredit'%}">Edit</a></p>
          {% endif %}
      </div>
    </div>
    <h3 style='color:#5993bb'>Your Coupons</h3>
    <div class="row">
      <table>
        <thead>
          <tr>
            <th class="text-center">Coupon</th>
            <th class="text-center">Discount</th>
            <th class="text-center">Status</th>
          </tr>
        </thead>
        <tbody>
          {% for coupon in user.coupons.all %}
            <tr class="num">
              <td class="text-center">"{{ coupon.code }}"</td>
              <td class = "text-center">{{ coupon.discount }}% off for products {{coupon.seller}}</td>
              {% if coupon.active %}
                {% if coupon.cart %}
                  <td class="text-warning text-center">In the cart</td>
                {% else %}
                  <td class="text-success text-center">Available</td>
                {% endif %}
              {% else %}
                <td class="text-danger text-center">Used</td>
              {% endif %}
            </tr>
          {% empty %}
            <p>No coupons</p>
          {% endfor%}
        </tbody>
      </table>
    </div>
  </div>
{% endblock%}

templates/shop/useredit.html
{% extends 'shop/base.html' %}
{% block content %}
<h1>Edit</h1>
<form action="." method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ user.as_p}}
  {{profile.as_p}}
  <input type="submit" value="Update" />
</form>
{% endblock%}