cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name = 'cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name = 'cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name = 'cart_remove'),

]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('cart/', include('cart.urls', namespace = 'cart')),
    path('', include('shop.urls', namespace = 'shop')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('seller/', include('sellers.urls', namespace='sellers')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name = 'product_list'),
    path('<slug:category_slug>/', views.product_list, name = 'product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name = 'product_detail'),
    path('add_product', views.add_product, name = 'add_product'),
    path('edit_product/<int:id>/<slug:slug>/', views.edit_product, name = 'edit_product'),
    path('delete_product/<int:id>/<slug:slug>/', views.delete_product, name = 'delete_product'),
    path('update_average', views.update_avg, name='update_average'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/models.py
from django.db import models
from django.shortcuts import reverse
from sellers.models import Seller
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db.models import Avg
from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
from datetime import datetime

class Category(models.Model):
    name = models.CharField(max_length = 200, db_index = True)
    slug = models.SlugField(max_length = 200, unique = True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    seller=models.ForeignKey(Seller, on_delete=models.CASCADE, related_name='products')
    category = models.ForeignKey(Category, related_name = 'products', on_delete = models.CASCADE)
    name = models.CharField(max_length = 200, db_index = True)
    slug = models.SlugField(max_length = 200, db_index = True)
    image = models.ImageField(upload_to = 'products/%Y/%m/%d', blank = True)
    description = models.TextField(blank = True)
    price = models.DecimalField(max_digits = 10, decimal_places = 2)
    available = models.BooleanField(default = True)
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now = True)
    quantity = models.PositiveIntegerField(default = 0)
    purchased_quantity = models.PositiveIntegerField(default = 0)
    rating_average = models.FloatField(default=0)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])


    def save(self, *args, **kwargs):
        if not self.id:
            self.image = self.compress_image(self.image)
        super(Product, self).save(*args, **kwargs)

    def compress_image(self, uploaded_image):
        img = Image.open(uploaded_image)
        outputIoStream = BytesIO()
        img = img.resize((400, 400))
        img.save(outputIoStream , format='JPEG', quality=80)
        outputIoStream.seek(0)
        uploaded_image = InMemoryUploadedFile(outputIoStream,'ImageField', "%s.jpg" % uploaded_image.name.split('.')[0], 'image/jpeg', None, None)
        return uploaded_image


class ProductRating(models.Model):
    rating = models.FloatField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='product_rating')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='rating')

    class Meta():
        ordering=['id']
        unique_together = (("user", "product"),)

    def __str__(self):
        return '{}-{}'.format(str(self.product), str(self.rating))


@receiver(post_save, sender=ProductRating)
def update_average(sender, instance, **kwargs):
    product = instance.product
    product.rating_average = product.rating.all().aggregate(Avg('rating'))['rating__avg']
    product.save(update_fields=['rating_average'])

class ProductReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='product_reviews')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='reviews')
    text = models.TextField(max_length=1000)
    date = models.DateTimeField(default=datetime.now, verbose_name='Date')

    class Meta():
        ordering=['id']

    def __str__(self):
        return '{} review .User {}'.format(str(self.product), str(self.user))

shop/forms.py
from django import forms
from .models import Product, ProductReview


class ProductAddForm(forms.ModelForm):
    field_order = ['category', 'name', 'description', 'image', 'price', 'quantity']
    class Meta:
        model = Product
        fields = {'category', 'name', 'description', 'image', 'price','quantity'}

class ProductEditForm(forms.ModelForm):
    field_order = ['category', 'name', 'description', 'image', 'price','quantity', 'available']
    class Meta:
        model = Product
        fields = {'category', 'name', 'description', 'image', 'price', 'quantity','available'}

class ProductReviewForm(forms.ModelForm):
    class Meta:
        model = ProductReview
        fields = {'text'}

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.contrib.auth.models import User
from shop.models import Category, Product, ProductRating
from cart.forms import CartAddProductForm
from .recommender import Recommender
from .forms import ProductAddForm, ProductEditForm
from sellers.models import Seller
from django.template.defaultfilters import slugify
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db.models import Avg
from django.contrib.auth.decorators import login_required

from .forms import ProductReviewForm

def product_list(request, category_slug = None):
    categories = Category.objects.all()
    products = Product.objects.filter(available = True)

    if category_slug:
        category = get_object_or_404(Category, slug = category_slug)
        products = products.filter(category = category)
    else:
        category = None

    context = {
        'category': category,
        'categories': categories,
        'products': products,
    }

    return render(request, 'shop/product/list.html', context)

def product_detail(request, id, slug):
    product = get_object_or_404(Product, id = id, slug = slug, available = True)
    cart_add_product_form = CartAddProductForm()
    product_review_form = ProductReviewForm()
    r = Recommender()
    recommended_products = r.suggest_products_for([product], 4)

    if request.method=='POST' and request.user.is_authenticated:
        review = ProductReviewForm(request.POST)

        if review.is_valid():
            new_review = review.save(commit=False)
            new_review.user = request.user
            new_review.product = product
            new_review.save()
            return redirect(product.get_absolute_url())

    context = {
        'product': product,
        'cart_add_product_form': cart_add_product_form,
        'recommended_products': recommended_products,
        'product_review_form': product_review_form
    }

    return render(request, 'shop/product/detail.html', context)

@login_required
def add_product(request):
    product_form = ProductAddForm()
    is_seller = False
    if request.user.is_authenticated and request.user.seller:
        is_seller = True
        if request.method == "POST":
            product_form = ProductAddForm(request.POST, request.FILES)
            if product_form.is_valid():
                new_product = product_form.save(commit=False)
                new_product.slug = slugify(new_product.name)
                new_product.seller = request.user.seller
                new_product.save()
                return redirect(reverse('shop:product_detail', args=[new_product.id, new_product.slug]))

    else:
        return HttpResponse("<h1>You are not seller</h1>", status=403)

    return render(request, 'shop/product/add_product.html', {'product_form': product_form, 'is_seller': is_seller})

@login_required(login_url='accounts/login/')
def edit_product(request, id, slug):
    product=get_object_or_404(Product, id=id, slug=slug)
    if request.user.is_authenticated:
        if request.user != product.seller.user and not request.user.is_superuser:
            raise PermissionDenied
        if request.method=='POST':
            product_edit_form = ProductEditForm(instance=product, data=request.POST, files=request.FILES)

            if product_edit_form.is_valid():
                product_edit_form.save()

            return redirect(reverse('shop:product_detail', args=[product.id, product.slug]))
        else:
            product_edit_form = ProductEditForm(instance=product)

    return render(request, 'shop/product/edit_product.html', {'product_edit_form': product_edit_form})

@login_required(login_url='accounts/login/')
def delete_product(request, id, slug):
    product=get_object_or_404(Product, id=id, slug=slug)
    if request.user.is_authenticated:
        if request.user != product.seller.user and not request.user.is_superuser:
            raise PermissionDenied
        product.delete()
        return redirect('shop:product_list')

@login_required
def update_avg(request):
    if request.is_ajax():
        product = get_object_or_404(Product, id=request.POST.get('id'))
        rating = request.POST.get('rating')
        if ProductRating.objects.filter(user=request.user, product=product).exists():
            obj = ProductRating.objects.get(user=request.user, product=product)
            obj.rating = rating
            obj.save(update_fields=['rating'])
            product.rating_average = product.rating.all().aggregate(Avg('rating'))['rating__avg']
            product.save(update_fields=['rating_average'])

        else:
            ProductRating.objects.create(user=request.user, product=product, rating=rating)

        return JsonResponse({'total_rating': product.rating_average})

    return HttpResponse('Bad request', status=400)

templates/shop/product/add_product.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
 Add product
{% endblock %}

{% block content %}

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ product_form.as_p }}
    <input type="submit" name="add_product" value="Add product">
  </form>

  </div>
{% endblock %}

templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}{{ product.name }}{% endblock %}

{% block content %}
  <script src="http://code.jquery.com/jquery-1.11.3.min.js" charset="utf-8"></script>
  <script src='{% static "shop/js/rater.js" %}' charset="utf-8"></script>
  <script>
    $(document).ready(function()
    {
      $(".rate").rate();

      $('.rate').click(function() {
        let rating = $(this).attr('data-rate-value'); // .data() use caching
        let id = {{product.id}};
        $.ajax({
            type: 'POST',
            url: '{% url "shop:update_average" %}',
            data: {'id': id, 'rating': rating, 'csrfmiddlewaretoken': '{{csrf_token}}'},
            dataType: 'json',

            success: function(response){
              $(".rate").rate("setValue", response.total_rating);
            },
        });
      });
    });
  </script>

  <style>
    .rate
    {
      font-size: 35px;
      color: #0085a1;

    }
    .rate-base-layer
    {
      color: #0085a1;
    }
    .rate-hover-layer
    {
      color: #0085a1;
    }
  </style>

  <div class="product-detail">
    <!-- Rating stars -->
    <div class="rate" data-rate-value={{product.rating_average}}></div>

    <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/no_image.png' %}{% endif %}">
    <h1> {{ product.name }} </h1>
    <a href="{% url 'profile' product.seller.user.id %}">{{product.seller.name}}</a>
    <h2><a href="{{ product.category.get_absolute_url }}"> {{product.category }}</a></h2>

    <p class="price">$ {{ product.price }} </p>
    <h6> available quantity {{ product.quantity }} </h6>
    <h6> purchased quantity {{ product.purchased_quantity }} </h6>
    <a href="{% url 'shop:edit_product' product.id product.slug %}">EDIT</a>
    <a href="{% url 'shop:delete_product' product.id product.slug %}">DELETE</a>

    <form action="{% url 'cart:cart_add' product.id %}" method="post">
      {{ cart_add_product_form }}
      {% csrf_token %}
      <input type="submit" value="Add to cart">
    </form>
    {{ product.description|linebreaks }}

    <h3 style="color:#5993bb">Reviews</h3>
    <br>
    {% for review in product.reviews.all %}
      <h6>{{ review.text }}</h6>
      <h6>Posted by {{ review.user }}</h6>
      <h6>{{ review.date }}</h6>
      <hr>
    {% empty %}
      <h6>No reviews</h6>
    {% endfor %}

    {% if request.user.is_authenticated %}
      <form method="post">
        {% csrf_token %}
        {{ product_review_form.as_p }}
        <input type="submit" value="Add Review">
      </form>
    {% endif %}

    {% if recommended_products %}
      <div class="recommendations">
        <h3>People who bought this also bought</h3>
        {% for p in recommended_products %}
          <div class="item">
            <a href="{{ p.get_absolute_url }}">
            <img  src='{% if p.image %}{{ p.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}'></a>
            <p><a href="{{ p.get_absolute_url }}">{{ p.name }}</a></p>
          </div>
        {% endfor %}
      </div>
    {% endif %}
  </div>
{% endblock %}

templates/shop/product/edit_product.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
 Add product
{% endblock %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ product_edit_form.as_p }}
    <input type="submit" name="edit_product" value="Edit product">
  </form>
{% endblock %}

templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}

  <div id="sidebar">
    <h3>Categories</h3>
    <ul>
      <li {% if not category %} class="selected" {% endif %}>
        <a href="{% url 'shop:product_list' %}"> All </a>
      </li>
      {% for c in categories %}
        <li {% if category.slug == c.slug %} class="selected" {% endif %}>
            <a href="{{ c.get_absolute_url }}"> {{ c.name }} </a>
        </li>
      {% endfor %}
    </ul>
  </div>
  <div id="main" class="product-list">
    <h1>{% if category %} {{ category.name }} {% else %} Products {% endif %}</h1>
    {% for product in products %}
      <div class="item">
          <a href="{{ product.get_absolute_url }}">
            <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/no_image.png' %} {% endif %}">
          </a>
          <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
          ${{ product.price }}
      </div>
    {% endfor %}
  </div>
{% endblock %}